name: Run Scheduled Action
on:
  push:
    branches: main
  workflow_dispatch:
  repository_dispatch:
    types: [run_stumpy_growth]
jobs:
  get_stumpy_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Retrieve STUMPY Stats
        run: bash github.sh ${WEBHOOK}
        shell: bash
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          PEPY_TECH: ${{ secrets.PEPY_TECH_API_KEY}}
